sonar.projectKey=pb-admin1_pb_webapplication
sonar.organization=pb-admin1
# Source code directories to be analyzed
sonar.sources=application

# Include only specific directories
sonar.inclusions=application/modules/**

# Optionally, you can also specify tests to include only specific test directories
# sonar.tests=tests
# sonar.test.inclusions=tests/unit/**,tests/integration/**


# Exclusions (if you need to exclude some files from the included directories)
# sonar.exclusions=src/main/legacy/**,src/utils/temp/**
#

