packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

variable "github_token" {
  type = string
}

variable "instance_type" {
  type    = string
  default = "c5.large"
}

variable "region" {
  type    = string
  default = "ap-south-1"
}

variable "repository" {
  type    = string
  default = "pb-admin1/pb_webapplication.git"
}

variable "branch" {
  type    = string
  default = "master"
}

variable "config_repository" {
  type    = string
  default = "pb-admin1/pb-config"
}

variable "config_branch" {
  type    = string
  default = "main"
}

variable "source_ami" {
  type    = string
  default = "ami-0b6152a3eee8a6bde"
}

variable "ssh_username" {
  type    = string
  default = "ubuntu"
}

variable "vpc_id" {
  type    = string
  default = "vpc-0708622df34ce2620"
}

variable "subnet_id" {
  type    = string
  default = "subnet-0e2eaf6fc179b7347"
}

variable "volume_size" {
  type    = number
  default = 20
}

variable "volume_type" {
  type    = string
  default = "gp3"
}

variable "environment" {
  type    = string
  default = "production" # or "sandbox"
}


#variable "iam_instance_profile" {
#  type    = string
#  default = "s3-access-goldenami-cicd-prod"
#}

source "amazon-ebs" "autogenerated_1" {
  ami_name              = "PB-WEBSITE-${formatdate("YYYY-MM-DD-hhmmss", timestamp())}"
  instance_type         = var.instance_type
  region                = var.region
  source_ami            = var.source_ami
  ssh_username          = var.ssh_username
  vpc_id                = var.vpc_id
  subnet_id             = var.subnet_id
  #iam_instance_profile  = var.iam_instance_profile
  launch_block_device_mappings {
        device_name = "/dev/sda1"
        volume_size = 20
        volume_type = "gp3"
    }
  tags = {
    Name = "PB-WEBSITE-PROD"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
  inline = [
    "sudo rm -rf /var/www/html/*",
    "if [ -d /var/www/html ]; then sudo rm -rf /var/www/html; fi",
    "sudo mkdir -p /var/www/html",
    "sudo git config --global http.postBuffer 524288000",
    "sudo git config --global credential.helper 'cache --timeout=3600'",
    "sudo bash -c 'echo \"https://push-code:${var.github_token}@github.com\" > ~/.git-credentials'",
    "sudo git clone --branch ${var.branch} https://push-code:${var.github_token}@github.com/${var.repository} /var/www/html",
    "if [ $? -eq 0 ]; then echo 'Repository successfully cloned'; else echo 'Failed to clone repository'; fi",
    "sudo chown -R www-data:www-data /var/www/html/",
    "sudo rm -rf /var/www/html/.git",
    "sudo rm -rf /var/www/html/.github",
    "sudo rm -rf /var/www/html/.gitignore",
    "sudo rm /var/www/html/template.json.pkr.hcl",
    "sudo rm /var/www/html/sonar-project.properties",
    "sudo chmod -R 777 /var/www/html/"
    ]
  }
  provisioner "shell" {
    inline = [
      "sudo mkdir -p /var/www/html/config",
      "sudo git clone --branch ${var.config_branch} https://push-code:${var.github_token}@github.com/${var.config_repository} /var/www/html/config",
      "sudo cp /var/www/html/config/website/${var.environment}/.htaccess /var/www/html/.htaccess",
      "sudo cp /var/www/html/config/website/${var.environment}/robots.txt /var/www/html/robots.txt",
      "sudo rm -rf /var/www/html/config/",
      "sudo rm -rf /var/www/html/.git",
      "sudo rm -rf /var/www/html/.github",
      "sudo rm -rf /var/www/html/.gitignore",
      "sudo chmod -R 777 /var/www/html/"
    ]
  }
  # Cleanup provisioner to remove Git credentials
  provisioner "shell" {
    inline = [
      "sudo rm -f ~/.git-credentials",
      "sudo git config --global --unset credential.helper"
    ]
  }
}
